/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Events.h
#pragma once

#include "Core.h"
#include "ECS/EventDispatcher.h"
#include "ECS/Registry/Entity.h"
#include "glm/ext/vector_float2.hpp"
#include <sol/state.hpp>

namespace pain
{

/**
 * Event emitted when the ImGui viewport changes size.
 *
 * This event is typically generated by the editor or windowing layer
 * and propagated to systems that need to react to viewport resizing.
 */
struct ImGuiViewportChangeEvent {
  glm::vec2 newSize;

  /** Converts this event into a Lua table representation. */
  sol::table toLuaTable(const sol::state &lua) const
  {
    return lua.create_table_with( //
        lua,                      //
        "newSize", newSize        //
    );
  }
};

/**
 * Event emitted when two entities collide.
 *
 * Contains the involved entities, collision normal, and penetration depth.
 * This event can be forwarded to Lua when listed in EVENT_TYPE_LIST.
 */
struct CollisionEvent {
  reg::Entity a;
  reg::Entity b;
  glm::vec2 normal;
  float penetration;

  /** Converts this event into a Lua table representation. */
  sol::table toLuaTable(const sol::state &lua) const
  {
    return lua.create_table_with(  //
        lua,                       //
        "a", a,                    //
        "b", b,                    //
        "normal", normal,          //
        "penetration", penetration //
    );
  }
};

/**
 * List of event types synchronized with Lua.
 *
 * Events declared in this list are automatically:
 * - Exposed to Lua through the EventType enum.
 * - Subscribable using Event.subscribe(...) from Lua.
 *
 * Events not present in this list remain engine-only and cannot be
 * subscribed from Lua unless registered through the custom event API.
 *
 * Usage:
 *   X(EventStructType, LuaVisibleName)
 */
#define EVENT_TYPE_LIST X(CollisionEvent, Collision)

/**
 * Creates and registers the Lua Event API.
 *
 * This function binds:
 * - Event.subscribe(...) for engine-defined events.
 * - Event.subscribeCustom(...) for user-defined event IDs.
 * - Event.enqueueCustom(...) for pushing custom events from Lua.
 * - EventType enum reflecting EVENT_TYPE_LIST.
 *
 * @param lua Lua state to extend.
 * @param reg Event dispatcher used for subscription and dispatch.
 * @return Reference to the same Lua state for chaining.
 */
sol::state &createLuaEventMap(sol::state &lua, reg::EventDispatcher &reg);

} // namespace pain
