#pragma once

#include <SDL2/SDL.h>
#include <SDL2/SDL_video.h>
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <glad/gl.h>
#include <glm/fwd.hpp>
#include <glm/glm.hpp>
#include <memory>
#include <spdlog/logger.h>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
